const arr = [
  {
    id: "1",
    img: "/img/1.png",
    header: "header",
    text: "text",
    price: "25000",
    weight: "500",
    quantity: 0,
  },
  {
    id: "2",
    img: "/img/2.png",
    header: "header",
    text: "text",
    price: "205",
    weight: "55",
    quantity: 0,
  },
  {
    id: "3",
    img: "/img/3.png",
    header: "header",
    text: "text",
    price: "259",
    weight: "25",
    quantity: 0,
  },
  {
    id: "4",
    img: "/img/4.png",
    header: "header",
    text: "text",
    price: "425",
    weight: "95",
    quantity: 0,
  },
  {
    id: "5",
    img: "/img/1.png",
    header: "header",
    text: "text",
    price: "25000",
    weight: "5",
    quantity: 0,
  },
  {
    id: "6",
    img: "/img/2.png",
    header: "header",
    text: "text",
    price: "205",
    weight: "55",
    quantity: 0,
  },
  {
    id: "7",
    img: "/img/3.png",
    header: "header",
    text: "text",
    price: "259",
    weight: "25",
    quantity: 0,
  },
  {
    id: "8",
    img: "/img/4.png",
    header: "header",
    text: "text",
    price: "425",
    weight: "95",
    quantity: 0,
  },
];

export default arr;
